microsocial2/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import set_language
from microsocial2 import views


urlpatterns = [
    url(
        r'^$',
        views.main,
        name='main'
    ),
    url(
        r'^i18n/setlang/$',
        csrf_exempt(set_language),
        name='set_language'
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('users.urls')),
    url(r'', include('auths.urls')),
    url(r'', include('dialogs.urls')),
    url(r'', include('news.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))


urlpatterns.extend([
    url(r'', include('django.contrib.flatpages.urls')),
])

news/urls.py
from django.conf.urls import url
from news import views


urlpatterns = [
    url(
        r'^news/$',
        views.NewsView.as_view(),
        name='news'
    ),
]

users/urls.py
from django.conf.urls import url
from users import views


urlpatterns = [
    url(
        r'^profile/(?P<user_id>\d+)/$',
        views.UserProfileView.as_view(),
        name='user_profile'
    ),
    url(
        r'^settings/$',
        views.UserSettingsView.as_view(),
        name='user_settings'
    ),
    url(
        r'^friends/$',
        views.UserFriendsView.as_view(),
        name='user_friends'
    ),
    url(
        r'^friends/incoming/$',
        views.UserIncomingView.as_view(),
        name='user_incoming'
    ),
    url(
        r'^friends/outcoming/$',
        views.UserOutcomingView.as_view(),
        name='user_outcoming'
    ),
    url(
        r'^api/friendship/$',
        views.FriendshipAPIView.as_view(),
        name='user_friendship_api'
    ),
    url(
        r'^search/$',
        views.SearchView.as_view(),
        name='user_search'
    ),
]

users/models.py
# coding=utf-8
import hashlib
import os
import datetime
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.core.signing import Signer, TimestampSigner
from django.core.urlresolvers import reverse
from django.db import models, transaction
from django.db.models import Q
from django.dispatch import Signal
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext, ugettext_lazy as _


def get_ids_from_users(*users):
    return [user.pk if isinstance(user, User) else int(user) for user in users]


class UserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_active=True, is_superuser=is_superuser,
                          last_login=now, date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class UserFriendShipManager(models.Manager):
    def are_friends(self, user1, user2):
        user1_id, user2_id = get_ids_from_users(user1, user2)
        return self.filter(pk=user1_id, friends__pk=user2_id).exists()

    @transaction.atomic
    def add(self, user1, user2):
        user1_id, user2_id = get_ids_from_users(user1, user2)
        if user1_id == user2_id:
            raise ValueError(_(u'Нельзя самого себя добавить в друзья.'))
        if not self.are_friends(user1_id, user2_id):
            through_model = self.model.friends.through
            through_model.objects.bulk_create([
                through_model(from_user_id=user1_id, to_user_id=user2_id),
                through_model(from_user_id=user2_id, to_user_id=user1_id),
            ])
            FriendInvite.objects.filter(
                Q(from_user_id=user1_id, to_user_id=user2_id) | Q(from_user_id=user2_id, to_user_id=user1_id)
            ).delete()
            make_friends.send(self.model, user1_id=user1_id, user2_id=user2_id)
            return True

    def delete(self, user1, user2):
        user1_id, user2_id = get_ids_from_users(user1, user2)
        if self.are_friends(user1_id, user2_id):
            through_model = self.model.friends.through
            through_model.objects.filter(
                Q(from_user_id=user1_id, to_user_id=user2_id) | Q(from_user_id=user2_id, to_user_id=user1_id)
            ).delete()
            break_friends.send(self.model, user1_id=user1_id, user2_id=user2_id)
            return True


def get_avatar_fn(instance, filename):
    id_str = str(instance.pk)
    return 'avatars/{sub_dir}/{id}_{rand}{ext}'.format(
        sub_dir=id_str.zfill(2)[-2:],
        id=id_str,
        rand=get_random_string(8, 'abcdefghijklmnopqrstuvwxyz0123456789'),
        ext=os.path.splitext(filename)[1],
    )


class User(AbstractBaseUser, PermissionsMixin):
    SEX_NONE = 0
    SEX_MALE = 1
    SEX_FEMALE = 2
    SEX_CHOICES = (
        (SEX_NONE, _(u'------')),
        (SEX_MALE, _(u'мужской')),
        (SEX_FEMALE, _(u'женский')),
    )
    email = models.EmailField(_('email'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    confirmed_registration = models.BooleanField(_('confirmed registration'), default=True)
    avatar = models.ImageField(_(u'аватар'), upload_to=get_avatar_fn, blank=True)
    sex = models.SmallIntegerField(_(u'пол'), choices=SEX_CHOICES, default=SEX_NONE)
    birth_date = models.DateField(_(u'дата рождения'), null=True, blank=True)
    city = models.CharField(_(u'город'), max_length=50, blank=True)
    job = models.CharField(_(u'место работы'), max_length=200, blank=True)
    about_me = models.TextField(_(u'о себе'), max_length=10000, blank=True)
    interests = models.TextField(_(u'интересы'), max_length=10000, blank=True)
    friends = models.ManyToManyField('self', verbose_name=_(u'друзья'), symmetrical=True, blank=True)

    objects = UserManager()
    friendship = UserFriendShipManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_last_login_hash(self):
        return hashlib.md5(self.last_login.strftime('%Y-%m-%d-%H-%M-%S-%f')).hexdigest()[:8]

    def send_registration_email(self):
        url = 'http://{}{}'.format(
            Site.objects.get_current().domain,
            reverse('registration_confirm', kwargs={'token': Signer(salt='registration-confirm').sign(self.pk)})
        )
        self.email_user(
            ugettext(u'Подтвердите регистрацию на Microsocial'),
            ugettext(u'Для подтверждения перейдите по ссылке: {}').format(url)
        )

    def send_password_recovery_email(self):
        data = '{}:{}'.format(self.pk, self.get_last_login_hash())
        token = TimestampSigner(salt='password-recovery-confirm').sign(data)
        url = 'http://{}{}'.format(
            Site.objects.get_current().domain,
            reverse('password_recovery_confirm', kwargs={'token': token})
        )
        self.email_user(
            ugettext(u'Подтвердите восстановление пароля на Microsocial'),
            ugettext(u'Для подтверждения перейдите по ссылке: {}').format(url)
        )

    def get_age(self):
        if self.birth_date:
            return int((datetime.date.today() - self.birth_date).days / 365.2425)


class FriendInviteManager(models.Manager):
    def is_pending(self, from_user, to_user):
        """
        Проверяет, существует ли заявка от пользователя from_user пользователю to_user.
        """
        from_user_id, to_user_id = get_ids_from_users(from_user, to_user)
        return self.filter(from_user_id=from_user_id, to_user_id=to_user_id).exists()

    def add(self, from_user, to_user):
        """
        Создает заявку.
        Возвращает 1, если заявка создана и 2, если пользователи теперь друзья.
        """
        from_user_id, to_user_id = get_ids_from_users(from_user, to_user)
        if from_user_id == to_user_id:
            raise ValueError(_(u'Нельзя самого себя добавить в друзья.'))
        if User.friendship.are_friends(from_user_id, to_user_id):
            raise ValueError(_(u'Вы уже друзья.'))
        if self.is_pending(from_user_id, to_user_id):
            raise ValueError(_(u'Заявка уже создана и ожидает рассмотрения.'))
        if self.is_pending(to_user_id, from_user_id):  # если существует заявка от to_user к from_user
            User.friendship.add(from_user_id, to_user_id)
            return 2
        self.create(from_user_id=from_user_id, to_user_id=to_user_id)
        return 1

    def approve(self, from_user, to_user):
        """
        Подтверждает заявку в друзья.
        """
        from_user_id, to_user_id = get_ids_from_users(from_user, to_user)
        if not self.is_pending(from_user_id, to_user_id):
            raise ValueError(_(u'Заявка не существует.'))
        return User.friendship.add(from_user_id, to_user_id)

    def reject(self, from_user, to_user):
        """
        Отклоняет заявку в друзья.
        """
        from_user_id, to_user_id = get_ids_from_users(from_user, to_user)
        self.filter(from_user_id=from_user_id, to_user_id=to_user_id).delete()


class FriendInvite(models.Model):
    from_user = models.ForeignKey(User, related_name='out_friend_invites')
    to_user = models.ForeignKey(User, related_name='in_friend_invites')

    objects = FriendInviteManager()

    class Meta:
        unique_together = ('from_user', 'to_user')


class UserWallPost(models.Model):
    user = models.ForeignKey(User, verbose_name=_(u'владелец стены'), related_name='wall_posts')
    author = models.ForeignKey(User, verbose_name=_(u'автор'), related_name='+')
    content = models.TextField(_(u'текст'), max_length=5000)
    created = models.DateTimeField(_(u'дата'), auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)


make_friends = Signal(providing_args=['user1_id', 'user2_id'])
break_friends = Signal(providing_args=['user1_id', 'user2_id'])

users/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.core import validators
from django.utils.translation import ugettext, ugettext_lazy as _
from microsocial2.forms import BootstrapFormMixin
from users.models import User, UserWallPost


class UserProfileForm(forms.ModelForm, BootstrapFormMixin):
    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'sex', 'birth_date', 'city', 'job', 'about_me', 'interests')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)
        self.fields['birth_date'].widget.attrs['placeholder'] = ugettext(u'Введите дату в формате ГГГГ-ММ-ДД')


class UserPasswordChangeForm(PasswordChangeForm, BootstrapFormMixin):
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)
        for field_name in ('old_password', 'new_password1', 'new_password2'):
            self.fields[field_name] = self.fields.pop(field_name)
            if field_name != 'old_password':
                self.fields[field_name].validators.extend([validators.MinLengthValidator(6),
                                                           validators.MaxLengthValidator(40)])


class UserEmailChangeForm(forms.Form, BootstrapFormMixin):
    new_email = forms.EmailField(max_length=75, label=_(u'новый email'))
    password = forms.CharField(label=_(u'текущий пароль'), widget=forms.PasswordInput())

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserEmailChangeForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)

    def clean_new_email(self):
        new_email = self.cleaned_data['new_email'].strip()
        if User.objects.filter(email=new_email).exclude(pk=self.user.pk).exists():
            raise forms.ValidationError(_(u'Пользователь с таким email уже существует.'))
        return new_email

    def clean_password(self):
        password = self.cleaned_data['password']
        if not self.user.check_password(password):
            raise forms.ValidationError(_(u'Введен неправильный пароль.'))
        return password

    def save(self, commit=True):
        self.user.email = self.cleaned_data['new_email']
        if commit:
            self.user.save()
        return self.user


class UserWallPostForm(forms.ModelForm, BootstrapFormMixin):
    class Meta:
        model = UserWallPost
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4, 'placeholder': _(u'напишите на стене...')}),
        }

    def __init__(self, *args, **kwargs):
        super(UserWallPostForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)

    def clean_content(self):
        return self.cleaned_data['content'].strip()


class SearchForm(forms.Form, BootstrapFormMixin):
    name = forms.CharField(label=_(u'имя, фамилия'), required=False)
    sex = forms.TypedChoiceField(label=_(u'пол'), required=False,
                                 choices=((0, _(u'все')),) + User.SEX_CHOICES[1:],
                                 coerce=lambda val: int(val))
    by_from = forms.IntegerField(label=_(u'год рождения от'), required=False,
                                 widget=forms.NumberInput(attrs={'placeholder': _(u'от')}))
    by_to = forms.IntegerField(label=_(u'год рождения до'), required=False,
                               widget=forms.NumberInput(attrs={'placeholder': _(u'до')}))
    city = forms.CharField(label=_(u'город'), required=False)
    job = forms.CharField(label=_(u'место работы'), required=False)
    about_me = forms.CharField(label=_(u'о себе'), required=False)
    interests = forms.CharField(label=_(u'интересы'), required=False)

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)

    def get_values_list(self, field_name):
        val = self.cleaned_data.get(field_name)
        if isinstance(val, basestring):
            val = val.strip().split()
        return val or []

users/templates/users/friends_base.html
{% extends 'base.html' %}

{% load i18n %}


{% block content %}
    <div class="row">
        <div class="col-sm-3">
            <ul class="nav nav-pills nav-stacked" style="margin-top: 20px;">
                <li{% if friends_menu == 'friends' %} class="active"{% endif %}>
                    <a href="{% url 'user_friends' %}">{% trans 'друзья'|capfirst %}</a>
                </li>
                <li{% if friends_menu == 'incoming' %} class="active"{% endif %}>
                    <a href="{% url 'user_incoming' %}">{% trans 'входящие заявки'|capfirst %}</a>
                </li>
                <li{% if friends_menu == 'outcoming' %} class="active"{% endif %}>
                    <a href="{% url 'user_outcoming' %}">{% trans 'исходящие заявки'|capfirst %}</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-9">
            {% block friends_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

users/templates/users/friends_friends.html
{% extends 'users/friends_base.html' %}

{% load i18n users microsocial %}


{% block friends_content %}
    <h1>{% trans 'друзья'|capfirst %}</h1>

    {% for item in items %}
        <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
            <div class="col-sm-2">
                <img class="img-responsive" src="{{ item|get_avatar }}">
            </div>
            <div class="col-sm-9">
                <h3 style="margin-top: 0;">
                    <a href="{% url 'user_profile' item.pk %}">{{ item.get_full_name }}</a>
                </h3>
                <p>
                    <form action="{% url 'user_friendship_api' %}" method="post" style="display: inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="delete_from_friends">
                        <input type="hidden" name="user_id" value="{{ item.pk }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <input type="submit" class="btn btn-danger btn-sm"
                               value="{% trans 'удалить из друзей'|capfirst %}">
                    </form>
                </p>
                <p>
                    <a href="{% url 'messages' item.pk %}">{% trans 'написать сообщение'|capfirst %}</a>
                </p>
            </div>
        </div>
    {% endfor %}

    {% show_paginator items %}

{% endblock %}

users/templates/users/friends_incoming.html
{% extends 'users/friends_base.html' %}

{% load i18n users microsocial %}


{% block friends_content %}
    <h1>{% trans 'входящие заявки'|capfirst %}</h1>

    {% for item in items %}
        <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
            <div class="col-sm-2">
                <img class="img-responsive" src="{{ item.from_user|get_avatar }}">
            </div>
            <div class="col-sm-9">
                <h3 style="margin-top: 0;">
                    <a href="{% url 'user_profile' item.from_user.pk %}">{{ item.from_user.get_full_name }}</a>
                </h3>
                <p>
                    <form action="{% url 'user_friendship_api' %}" method="post" style="display: inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="approve">
                        <input type="hidden" name="user_id" value="{{ item.from_user.pk }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <input type="submit" class="btn btn-success btn-sm"
                               value="{% trans 'подтвердить'|capfirst %}">
                    </form>
                    <form action="{% url 'user_friendship_api' %}" method="post" style="display: inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="reject">
                        <input type="hidden" name="user_id" value="{{ item.from_user.pk }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <input type="submit" class="btn btn-danger btn-sm"
                               value="{% trans 'отклонить'|capfirst %}">
                    </form>
                </p>
            </div>
        </div>
    {% endfor %}

    {% show_paginator items %}

{% endblock %}

users/templates/users/friends_outcoming.html
{% extends 'users/friends_base.html' %}

{% load i18n users microsocial %}


{% block friends_content %}
    <h1>{% trans 'исходящие заявки'|capfirst %}</h1>

    {% for item in items %}
        <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
            <div class="col-sm-2">
                <img class="img-responsive" src="{{ item.to_user|get_avatar }}">
            </div>
            <div class="col-sm-9">
                <h3 style="margin-top: 0;">
                    <a href="{% url 'user_profile' item.to_user.pk %}">{{ item.to_user.get_full_name }}</a>
                </h3>
                <p>
                    <form action="{% url 'user_friendship_api' %}" method="post" style="display: inline-block">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="cancel_outcoming">
                        <input type="hidden" name="user_id" value="{{ item.to_user.pk }}">
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <input type="submit" class="btn btn-danger btn-sm"
                               value="{% trans 'отменить'|capfirst %}">
                    </form>
                </p>
            </div>
        </div>
    {% endfor %}

    {% show_paginator items %}

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% load i18n users humanize microsocial %}


{% block content %}
    <div class="row">
        <div class="col-xs-3">
            <div style="margin-top: 20px;">
                <img class="img-responsive" src="{{ profile_user|get_avatar }}">
            </div>
            <div class="text-center" style="margin-top: 10px;">
                {% if profile_user == user %}
                    <a href="{% url 'user_settings' %}">{% trans 'настройки'|capfirst %}</a>
                {% else %}
                    {% if is_my_friend %}
                        <form action="{% url 'user_friendship_api' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="delete_from_friends">
                            <input type="hidden" name="user_id" value="{{ profile_user.pk }}">
                            <input type="hidden" name="next" value="{{ request.get_full_path }}">
                            <input type="submit" class="btn btn-danger btn-sm"
                                   value="{% trans 'удалить из друзей'|capfirst %}">
                        </form>
                    {% else %}
                        <form action="{% url 'user_friendship_api' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="add_to_friends">
                            <input type="hidden" name="user_id" value="{{ profile_user.pk }}">
                            <input type="hidden" name="next" value="{{ request.get_full_path }}">
                            <input type="submit" class="btn btn-success"
                                   value="{% trans 'добавить в друзья'|capfirst %}">
                        </form>
                    {% endif %}
                    <div style="margin-top: 10px;">
                        <a href="{% url 'messages' profile_user.pk %}">
                            {% trans 'написать сообщение'|capfirst %}
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-xs-9">
            <h1>{{ profile_user.get_full_name }}</h1>
            <table class="table borderless">
            <tbody>
                {% if profile_user.sex %}
                    <tr>
                        <td>{% trans 'пол'|capfirst %}:</td>
                        <td>{{ profile_user.get_sex_display }}</td>
                    </tr>
                {% endif %}
                {% if profile_user.birth_date %}
                    <tr>
                        <td>{% trans 'дата рождения'|capfirst %}:</td>
                        <td>{{ profile_user.birth_date }}</td>
                    </tr>
                {% endif %}
                {% if profile_user.city %}
                    <tr>
                        <td>{% trans 'город'|capfirst %}:</td>
                        <td>{{ profile_user.city }}</td>
                    </tr>
                {% endif %}
                {% if profile_user.job %}
                    <tr>
                        <td>{% trans 'место работы'|capfirst %}:</td>
                        <td>{{ profile_user.job }}</td>
                    </tr>
                {% endif %}
                {% if profile_user.about_me %}
                    <tr>
                        <td>{% trans 'о себе'|capfirst %}:</td>
                        <td>{{ profile_user.about_me|linebreaksbr }}</td>
                    </tr>
                {% endif %}
                {% if profile_user.interests %}
                    <tr>
                        <td>{% trans 'интересы'|capfirst %}:</td>
                        <td>{{ profile_user.interests|linebreaksbr }}</td>
                    </tr>
                {% endif %}
            </tbody>
            </table>

            <form class="form" method="post">
                {% csrf_token %}
                {% show_form_field_errors wall_post_form.content.errors %}
                <div class="form-group{% if wall_post_form.content.errors %} has-error{% endif %}">
                    {{ wall_post_form.content }}
                </div>
                <input type="submit" class="btn btn-primary" value="{% trans 'опубликовать'|capfirst %}">
            </form>

            {% for wall_post in wall_posts %}
                <div style="margin-top: 20px; border: 1px solid #666; padding: 10px;">
                    <div class="row">
                        <div class="col-sm-2">
                            <img class="img-responsive" src="{{ wall_post.author|get_avatar }}">
                        </div>
                        <div class="col-sm-10">
                            <div>
                                <a href="{% url 'user_profile' wall_post.author_id %}">
                                    {{ wall_post.author.get_full_name }}
                                </a>
                                <span title="{{ wall_post.created }}" style="margin-left: 20px;">
                                    {{ wall_post.created|naturaltime }}
                                </span>
                            </div>
                            <div style="margin-top: 12px;">
                                {{ wall_post.content|linebreaksbr }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% show_paginator wall_posts %}
        </div>
    </div>
{% endblock %}

users/templates/users/search.html
{% extends 'base.html' %}

{% load i18n users microsocial %}


{% block content %}
    <h1 class="text-center">{% trans 'поиск людей'|capfirst %}</h1>

    <div class="row">
        <div class="col-sm-5">
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}" class="col-md-5 control-label">
                        {{ form.name.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.name }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.sex.id_for_label }}" class="col-md-5 control-label">
                        {{ form.sex.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.sex }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.by_from.id_for_label }}" class="col-md-5 control-label">
                        {% trans 'год рождения'|capfirst %}:
                    </label>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-xs-6">
                                {{ form.by_from }}
                            </div>
                            <div class="col-xs-6">
                                {{ form.by_to }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.city.id_for_label }}" class="col-md-5 control-label">
                        {{ form.city.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.city }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.job.id_for_label }}" class="col-md-5 control-label">
                        {{ form.job.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.job }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.about_me.id_for_label }}" class="col-md-5 control-label">
                        {{ form.about_me.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.about_me }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.interests.id_for_label }}" class="col-md-5 control-label">
                        {{ form.interests.label|capfirst }}:
                    </label>
                    <div class="col-md-7">
                        {{ form.interests }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-5 col-md-7">
                        <button type="submit" class="btn btn-primary">{% trans 'искать'|capfirst %}</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-7">
            {% for item in items %}
                <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
                    <div class="col-sm-2">
                        <img class="img-responsive" src="{{ item|get_avatar }}">
                    </div>
                    <div class="col-sm-10">
                        <h3 style="margin-top: 0;">
                            <a href="{% url 'user_profile' item.pk %}">{{ item.get_full_name }}</a>
                        </h3>
                        {% with age=item.get_age %}
                            {% if age %}
                                <p>{% blocktrans %}{{ age }} лет{% endblocktrans %}</p>
                            {% endif %}
                        {% endwith %}
                        {% if item.city %}
                            <p>{{ item.city }}</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

            {% show_paginator items %}
        </div>
    </div>
{% endblock %}